# Generated by Django 2.2.5 on 2021-03-10 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=10)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Canceled', 'Canceled')], default=('Approved', 'Approved'), max_length=20)),
                ('total', models.FloatField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='my_app.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField(default=0)),
                ('description', models.CharField(blank=True, max_length=400)),
                ('status', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
            ],
        ),
        migrations.CreateModel(
            name='Store_Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('in_stock_qty', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.Product')),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.Store')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qty', models.IntegerField(default=0)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='my_app.Order')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='my_app.Product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='store_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='my_app.Store'),
        ),
    ]
